require("configs/marks")()
require("configs/basic")()

require("configs/cmp").setup()
require("configs/mason").setup()
require("configs/telescope").setup()
require("configs/lsp").setup()
require("configs/trouble").setup()
require("configs/toggleterm").setup()
require("configs/lualine").setup()
require("configs/nvim-tree").setup()
require("configs/treesitter").setup()
require("configs/neogit").setup()
